app:
    resource: "@AppBundle/Controller/"
    type:     annotation

location:
    resource: "@ZoneBundle/Resources/config/routing.yml"
    prefix:   /region

indicateur:
    resource: "@IndicateurBundle/Resources/config/routing.yml"
    prefix:   /indicateurs

sco_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /utilisateurs

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"