zone_homepage:
    path:     /
    defaults: { _controller: ZoneBundle:Default:index }

zone_lister_region:
    path:     /lister_region
    defaults: { _controller: ZoneBundle:Region:lister }
    options:
        expose: true

zone_ajouter_region:
    path:     /ajouter_region
    defaults: { _controller: ZoneBundle:Region:ajouter }
    options:
        expose: true

zone_supprimer_region:
    path:     /supprimer_region/{id}
    defaults: { _controller: ZoneBundle:Region:supprimer }
    options:
        expose: true

zone_modifier_region:
    path:     /modifier_region/{id}
    defaults: { _controller: ZoneBundle:Region:modifier }
    options:
        expose: true




zone_lister_district:
    path:     /lister_district/{region_id}
    defaults: { _controller: ZoneBundle:District:lister }
    options:
        expose: true

zone_ajouter_district:
    path:     /ajouter_district/{region_id}
    defaults: { _controller: ZoneBundle:District:ajouter }
    options:
        expose: true

zone_supprimer_district:
    path:     /supprimer_district/{id}
    defaults: { _controller: ZoneBundle:District:supprimer }
    options:
        expose: true

zone_modifier_district:
    path:     /modifier_district/{id}
    defaults: { _controller: ZoneBundle:District:modifier }
    options:
        expose: true




zone_lister_commune:
    path:     /lister_commune/{district_id}
    defaults: { _controller: ZoneBundle:Commune:lister }
    options:
        expose: true

zone_ajouter_commune:
    path:     /ajouter_commune/{district_id}
    defaults: { _controller: ZoneBundle:Commune:ajouter }
    options:
        expose: true

zone_supprimer_commune:
    path:     /supprimer_commune/{id}
    defaults: { _controller: ZoneBundle:Commune:supprimer }
    options:
        expose: true

zone_modifier_commune:
    path:     /modifier_commune/{id}
    defaults: { _controller: ZoneBundle:Commune:modifier }
    options:
        expose: true